#include "Header.h"
int main() {
	return 0;
	/*CharecterData cD;
	cD.name = "brute";
	cD.hp = 14;
	cD.cardNum = 6;
	cD.totalcard = 8;
	struct CharecterCardData cCD;
	cCD.numero = 0;
	cCD.dexterity = 5;
	cCD.topHalf.str("attack 4");
	cCD.lowHalf.str("shield 2");
	cCD.cardStatus = 2;
	cD.card.push_back(cCD);
	cCD.numero = 1;
	cCD.dexterity = 14;
	cCD.topHalf.str("attack 3 range 3");
	cCD.lowHalf.str("move 3");
	cCD.cardStatus = 2;
	cD.card.push_back(cCD);
	cCD.numero = 2;
	cCD.dexterity = 20;
	cCD.topHalf.str("attack 3");
	cCD.lowHalf.str("move 4 heal 1");
	cCD.cardStatus = 2;
	cD.card.push_back(cCD);
	cCD.numero = 3;
	cCD.dexterity = 28;
	cCD.topHalf.str("attack 2 shield 1");
	cCD.lowHalf.str("move 3");
	cCD.cardStatus = 2;
	cD.card.push_back(cCD);
	cCD.numero = 4;
	cCD.dexterity = 37;
	cCD.topHalf.str("attack 2 attack 2");
	cCD.lowHalf.str("move 1 shield 1");
	cCD.cardStatus = 2;
	cD.card.push_back(cCD);
	cCD.numero = 5;
	cCD.dexterity = 49;
	cCD.topHalf.str("shield 2");
	cCD.lowHalf.str("attack 3 range 2");
	cCD.cardStatus = 2;
	cD.card.push_back(cCD);
	cCD.numero = 6;
	cCD.dexterity = 56;
	cCD.topHalf.str("heal 3");
	cCD.lowHalf.str("move 3");
	cCD.cardStatus = 2;
	cD.card.push_back(cCD);
	cCD.numero = 7;
	cCD.dexterity = 88;
	cCD.topHalf.str("attack 3");
	cCD.lowHalf.str("move 3");
	cCD.cardStatus = 2;
	cD.card.push_back(cCD);
	MonsterData mD;
	mD.name = "guard";
	mD.normal[0] = 3;
	mD.normal[1] = 2;
	mD.normal[2] = 0;
	mD.elite[0] = 6;
	mD.elite[1] = 3;
	mD.elite[2] = 0;
	MonsterCardData mCD;
	mCD.numero = 0;
	mCD.dexterity = 30;
	mCD.skill.str("move sd attack -1");
	mCD.cardStatus = 1;
	mCD.canShuffle = false;
	mD.card.push_back(mCD);
	mCD.numero = 1;
	mCD.dexterity = 55;
	mCD.skill.str("move wa attack 0");
	mCD.cardStatus = 1;
	mCD.canShuffle = false;
	mD.card.push_back(mCD);
	mCD.numero = 2;
	mCD.dexterity = 15;
	mCD.skill.str("shield 2");
	mCD.cardStatus = 1;
	mCD.canShuffle = true;
	mD.card.push_back(mCD);
	mCD.numero = 3;
	mCD.dexterity = 35;
	mCD.skill.str("move wd attack 0");
	mCD.cardStatus = 1;
	mCD.canShuffle = false;
	mD.card.push_back(mCD);
	mCD.numero = 4;
	mCD.dexterity = 50;
	mCD.skill.str("move sa attack 0");
	mCD.cardStatus = 1;
	mCD.canShuffle = false;
	mD.card.push_back(mCD);
	mCD.numero = 5;
	mCD.dexterity = 15;
	mCD.skill.str("shield 1 attack 0");
	mCD.cardStatus = 1;
	mCD.canShuffle = false;
	mD.card.push_back(mCD);
	Board b;
	MonsterPLace mP;
	mP.name = "archer";
	mP.place.col = 3;
	mP.place.row = 1;
	mP.peoNum[0] = 0;
	mP.peoNum[1] = 1;
	mP.peoNum[2] = 1;
	b.deploy.push_back(mP);
	mP.name = "archer";
	mP.place.col = 4;
	mP.place.row = 1;
	mP.peoNum[0] = 2;
	mP.peoNum[1] = 2;
	mP.peoNum[2] = 2;
	b.deploy.push_back(mP);
	mP.name = "archer";
	mP.place.col = 5;
	mP.place.row = 1;
	mP.peoNum[0] = 0;
	mP.peoNum[1] = 1;
	mP.peoNum[2] = 1;
	b.deploy.push_back(mP);
	mP.name = "guard";
	mP.place.col = 3;
	mP.place.row = 7;
	mP.peoNum[0] = 0;
	mP.peoNum[1] = 1;
	mP.peoNum[2] = 1;
	b.deploy.push_back(mP);
	mP.name = "guard";
	mP.place.col = 4;
	mP.place.row = 7;
	mP.peoNum[0] = 1;
	mP.peoNum[1] = 1;
	mP.peoNum[2] = 2;
	b.deploy.push_back(mP);
	mP.name = "guard";
	mP.place.col = 5;
	mP.place.row = 7;
	mP.peoNum[0] = 0;
	mP.peoNum[1] = 1;
	mP.peoNum[2] = 1;
	b.deploy.push_back(mP);*/
}